[build]
  # No build command needed for static site
  publish = "."

[build.environment]
  # Environment variables if needed
  NODE_VERSION = "18"

[[headers]]
  # Security headers for all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' data: https://unpkg.com https://*.tile.openstreetmap.org; img-src 'self' data: https://*.tile.openstreetmap.org; style-src 'self' 'unsafe-inline' https://unpkg.com; script-src 'self' 'unsafe-inline' https://unpkg.com; connect-src 'self' https://api.allorigins.win https://corsproxy.io https://cors-anywhere.herokuapp.com https://www.vesselfinder.com https://www.marinetraffic.com https://www.aishub.net https://www.myshiptracking.com"

[[headers]]
  # Cache static assets for 1 year
  for = "/style.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/api.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/map.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirect rules (if needed)
[[redirects]]
  from = "/beff"
  to = "/"
  status = 301

[[redirects]]
  from = "/track"
  to = "/"
  status = 301

# Custom 404 page
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200